export const CHECK_CATEGORIES = [
  { id: 'international', name: 'International SEO', icon: '🌐', checks: [1, 26, 27, 28, 37] },
  { id: 'technical', name: 'Fondation Technique', icon: '🔧', checks: [4, 18, 22, 23, 42, 44, 48, 49] },
  { id: 'content', name: 'Contenu & Structure', icon: '📝', checks: [3, 8, 9, 12, 32, 33, 35] },
  { id: 'schema', name: 'Schema & Données', icon: '📊', checks: [19, 21, 24, 25] },
  { id: 'media', name: 'Images & Médias', icon: '🖼️', checks: [2, 5] },
  { id: 'performance', name: 'Performance', icon: '⚡', checks: [6, 15, 20, 31, 34, 43, 46] },
  { id: 'javascript', name: 'JavaScript & Rendering', icon: '🔄', checks: [10, 30, 47] },
  { id: 'navigation', name: 'Navigation & Liens', icon: '🧭', checks: [11, 29, 36, 38, 39, 41] },
  { id: 'analysis', name: 'Analyse Technique', icon: '🔬', checks: [7, 13, 14, 16, 17, 45] },
  { id: 'errors', name: "Gestion d'Erreurs", icon: '🚫', checks: [40, 50] },
] as const;

export const CHECKS: Record<number, { name: string; weight: number; automatable: boolean }> = {
  1: { name: 'Balises hreflang', weight: 1, automatable: true },
  2: { name: 'Optimisation images', weight: 1, automatable: true },
  3: { name: "Fil d'Ariane (Breadcrumbs)", weight: 1, automatable: true },
  4: { name: 'HTTPS actif', weight: 1, automatable: true },
  5: { name: 'Optimisation fonts', weight: 1, automatable: true },
  6: { name: 'Optimisation CSS', weight: 1, automatable: true },
  7: { name: 'Analyse Crawl Stats', weight: 1, automatable: false },
  8: { name: 'Profondeur de clic', weight: 1, automatable: true },
  9: { name: 'Qualité des ancres', weight: 1, automatable: true },
  10: { name: 'Liens JavaScript', weight: 1, automatable: true },
  11: { name: 'Navigation mega menu', weight: 1, automatable: true },
  12: { name: 'Contenu suffisant', weight: 1, automatable: true },
  13: { name: 'Paramètres URL', weight: 1, automatable: true },
  14: { name: 'Contenu dupliqué', weight: 1, automatable: true },
  15: { name: 'Stratégie de cache', weight: 1, automatable: true },
  16: { name: 'Recherche interne', weight: 1, automatable: false },
  17: { name: 'Rapport Coverage', weight: 1, automatable: false },
  18: { name: 'Redirections trailing slash', weight: 1, automatable: true },
  19: { name: 'Données structurées avancées', weight: 1, automatable: true },
  20: { name: 'Chemin de rendu critique', weight: 1, automatable: true },
  21: { name: 'Validation Schema', weight: 1, automatable: true },
  22: { name: 'Redirections www/non-www', weight: 1, automatable: true },
  23: { name: 'Structure URL SEO-friendly', weight: 1, automatable: true },
  24: { name: 'Format JSON-LD', weight: 1, automatable: true },
  25: { name: 'Schema avancé', weight: 1, automatable: true },
  26: { name: 'Attribut lang', weight: 1, automatable: true },
  27: { name: 'Codes langue/pays', weight: 1, automatable: true },
  28: { name: 'Liens internationaux', weight: 1, automatable: true },
  29: { name: 'Navigation mobile', weight: 1, automatable: true },
  30: { name: 'Rendu côté client', weight: 1, automatable: true },
  31: { name: 'Performance utilisateur réel', weight: 1, automatable: false },
  32: { name: 'Liens internes spam', weight: 1, automatable: true },
  33: { name: 'Textes d\'ancre', weight: 1, automatable: true },
  34: { name: 'Performance serveur (TTFB)', weight: 1, automatable: true },
  35: { name: 'Pages orphelines', weight: 1, automatable: true },
  36: { name: 'Redirections internes', weight: 1, automatable: true },
  37: { name: 'Localisation contenu', weight: 1, automatable: false },
  38: { name: 'Pagination', weight: 1, automatable: true },
  39: { name: 'Stratégie filtres', weight: 1, automatable: false },
  40: { name: 'Page 404', weight: 1, automatable: true },
  41: { name: 'Liens nofollow internes', weight: 1, automatable: true },
  42: { name: 'Sitemap XML', weight: 1, automatable: true },
  43: { name: 'Optimisation JavaScript', weight: 1, automatable: true },
  44: { name: 'Liens HTTP', weight: 1, automatable: true },
  45: { name: 'Analyse logs serveur', weight: 1, automatable: false },
  46: { name: 'Analyse rendu', weight: 1, automatable: true },
  47: { name: 'Liens JS intelligents', weight: 1, automatable: true },
  48: { name: 'Balises canonical', weight: 1, automatable: true },
  49: { name: 'Robots.txt', weight: 1, automatable: true },
  50: { name: 'Liens cassés', weight: 1, automatable: true },
};
